zuul:
  route:
    student:
      id: Student
      path: /student/
server:
  port: 8080
spring:
  application:
    name: Zuul-Server
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
